import open3d as o3d
import laspy
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path


def visualize_las(las_path: Path):
    if not las_path.exists():
        raise FileNotFoundError(f"File not found: {las_path}")

    # 1. Load data via laspy
    las = laspy.read(str(las_path))
    points = np.vstack((las.x, las.y, las.z)).transpose()

    # 2. Extract distance scalar field
    # The name varies. If this fails, read the terminal output to find the correct string.
    if "M3C2" in str(las_path):
        dimension_name = "M3C2 distance"
    elif "C2C" in str(las_path):
        dimension_name = "C2C absolute distances"
    else:
        raise RuntimeError("Incorrect file loaded")

    if "M3C2" in str(las_path):
        dimension_name = "M3C2 distance"
    elif "C2C" in str(las_path):
        dimension_name = "C2C absolute distances"
    else:
        raise RuntimeError("Incorrect file loaded")

    try:
        # laspy accesses dimensions as attributes or dictionary keys
        distances = getattr(las, dimension_name)
    except AttributeError:
        dims = list(las.point_format.dimension_names)
        print(f"Available dimensions in LAS file: {dims}")
        raise ValueError(
            f"Could not find dimension matching '{dimension_name}'. Update the string."
        )

    # 3. Normalize distances to [0, 1] for the colormap
    # We clip the top 5% of distances. Outliers will ruin the visual gradient.

    abs_dist = np.abs(distances)
    p95 = np.percentile(abs_dist, 99)
    clipped_distances = np.clip(abs_dist, 0, p95)

    # Avoid division by zero if scans are identical
    max_dist = p95 if p95 > 0 else 1.0
    norm_distances = clipped_distances / max_dist
    # norm_distances = np.abs(norm_distances)

    # 4. Generate RGB values
    # 'turbo' is a perceptually uniform colormap, superior to 'jet' for identifying anomalies
    cmap = plt.get_cmap("turbo")
    colors = cmap(norm_distances)[:, :3]  # Slice off the alpha channel

    # 5. Build and render the Open3D geometry
    pcd = o3d.geometry.PointCloud()
    pcd.points = o3d.utility.Vector3dVector(points)
    pcd.colors = o3d.utility.Vector3dVector(colors)

    print("Rendering point cloud. Close the Open3D window to exit.")
    o3d.visualization.draw_geometries([pcd], window_name="C2C Distance Heatmap")

    return pcd, abs_dist


from damage_detection import DamageDetector

det = DamageDetector()

if __name__ == "__main__":
    # Point this to the file generated by the previous subprocess script
    # target_file = Path(
    #     r"..\data\Aligned_block_C2C_DIST_2026-04-23_16h54_08_450.las"
    # )
    # target_file = Path(r"..\data\CC\SRC_C2C_DIST_2026-04-24_09h43_25_767.las")
    target_file = Path(r"..\data\CC\sin_tgt_M3C2.las")
    # target_file = Path(r"..\data\CC\sin_src_reg_C2C_DIST_2026-04-24_12h39_24_664.las")
    pcd, distances = visualize_las(target_file)
    det.visualise_colourmap(pcd, distances)

    mean, std, thresh = det.estimate_noise(distances)
    mask = distances > thresh

    labels = det.cluster(pcd, mask, eps=0.2)
    det.color_point_cloud_by_labels(pcd, labels)
